### ISSUE TITLE
checkpoint file is not available

### ISSUE THREAD

**Issue by fengfengfeng666** [cpeng93/DiffuseRecon#2]
Hi, 
the link of your checkpoint file is not available. Could you please update this file?

**Comment by FlamePanda** [comment]
你好 [fengfengfeng666]，你能下载ScoreMRI的预训练模型吗，如果有的话，能不能发给我一份，谢谢啦，【抱拳】

**Comment by FlamePanda** [comment]
> Hi, the link to your checkpoint file is not available. Could you please update this file?
你好，[fengfengfeng666] 你能下载ScoreMRI的预训练模型吗，如果有的话，能不能发给我一份，谢谢啦，【抱拳】

**Comment by cpeng93** [comment]
Can you check to see if the link works now? I tried it myself without logging in and it seemed to work (if you exit the preview initially). I can also upload the checkpoint on google drive.

**Comment by fengfengfeng666** [comment]
> Can you check to see if the link works now? I tried it myself without logging in and it seemed to work (if you exit the preview initially). I can also upload the checkpoint on google drive.

Hi, the link of google drive is available. Thanks for your reply.

**Comment by fengfengfeng666** [comment]
> > Hi, the link to your checkpoint file is not available. Could you please update this file?
> > 你好，[fengfengfeng666] 你能下载ScoreMRI的预训练模型吗，如果有的话，能不能发给我一份，谢谢啦，【抱拳】

Hi, the author has uploaded a link with google driver. It is available for me. You could try yourself whether it works for you. The file of checkpoint is more than 500MB, if you still need it, I would send it to you with google drive.

**Comment by Four-Fire** [comment]
> 

Hi, can you share me with the file of checkpoint? I cann't download it from the two links, Thanks a lot.
